spring.application.name=JournalApp
spring.devtools.restart.enabled=true
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=journaldb
#spring.mongodb.username=user
#spring.mongodb.password=password
